tests:
  build: .
  environment:
    - NPM_USER
    - NPM_PASS
    - NPM_EMAIL
    - AWS_KEY
    - AWS_SECRET
    - BUILDKITE_MESSAGE
    - BUILDKITE_BRANCH
    - BUILDKITE_BUILD_URL
    - BUILDKITE_BUILD_NUMBER
    - BUILDKITE_COMMIT
    - BUILDKITE_JOB_ID
    - SLACK_WEBHOOK_URL
