'use strict';

export default [
  { label: 'Australia', value: 'AU', dial_code: '+61' },
  { label: 'Ireland', value: 'IE', dial_code: '+353' },
  { label: 'New Zealand', value: 'NZ', dial_code: '+64' },
  { label: 'United Kingdom', value: 'UK', dial_code: '+44' },
  { label: 'United States', value: 'US', dial_code: '+1' },
  { label: 'Canada', value: 'CA', dial_code: '+1' },
  { label: 'Afghanistan', value: 'AF', dial_code: '+93' },
  { label: 'Aland Islands', value: 'AX', dial_code: '+358' },
  { label: 'Albania', value: 'AL', dial_code: '+355' },
  { label: 'Algeria', value: 'DZ', dial_code: '+213' },
  { label: 'AmericanSamoa', value: 'AS', dial_code: '+1 684' },
  { label: 'Andorra', value: 'AD', dial_code: '+376' },
  { label: 'Angola', value: 'AO', dial_code: '+244' },
  { label: 'Anguilla', value: 'AI', dial_code: '+1 264' },
  { label: 'Antarctica', value: 'AQ', dial_code: '+672' },
  { label: 'Antigua and Barbuda', value: 'AG', dial_code: '+1268' },
  { label: 'Argentina', value: 'AR', dial_code: '+54' },
  { label: 'Armenia', value: 'AM', dial_code: '+374' },
  { label: 'Aruba', value: 'AW', dial_code: '+297' },
  { label: 'Austria', value: 'AT', dial_code: '+43' },
  { label: 'Azerbaijan', value: 'AZ', dial_code: '+994' },
  { label: 'Bahamas', value: 'BS', dial_code: '+1 242' },
  { label: 'Bahrain', value: 'BH', dial_code: '+973' },
  { label: 'Bangladesh', value: 'BD', dial_code: '+880' },
  { label: 'Barbados', value: 'BB', dial_code: '+1 246' },
  { label: 'Belarus', value: 'BY', dial_code: '+375' },
  { label: 'Belgium', value: 'BE', dial_code: '+32' },
  { label: 'Belize', value: 'BZ', dial_code: '+501' },
  { label: 'Benin', value: 'BJ', dial_code: '+229' },
  { label: 'Bermuda', value: 'BM', dial_code: '+1 441' },
  { label: 'Bhutan', value: 'BT', dial_code: '+975' },
  { label: 'Bolivia, Plurinational State of', value: 'BO', dial_code: '+591' },
  { label: 'Bosnia and Herzegovina', value: 'BA', dial_code: '+387' },
  { label: 'Botswana', value: 'BW', dial_code: '+267' },
  { label: 'Brazil', value: 'BR', dial_code: '+55' },
  { label: 'British Indian Ocean Territory', value: 'IO', dial_code: '+246' },
  { label: 'Brunei Darussalam', value: 'BN', dial_code: '+673' },
  { label: 'Bulgaria', value: 'BG', dial_code: '+359' },
  { label: 'Burkina Faso', value: 'BF', dial_code: '+226' },
  { label: 'Burundi', value: 'BI', dial_code: '+257' },
  { label: 'Cambodia', value: 'KH', dial_code: '+855' },
  { label: 'Cameroon', value: 'CM', dial_code: '+237' },
  { label: 'Cape Verde', value: 'CV', dial_code: '+238' },
  { label: 'Cayman Islands', value: 'KY', dial_code: '+ 345' },
  { label: 'Central African Republic', value: 'CF', dial_code: '+236' },
  { label: 'Chad', value: 'TD', dial_code: '+235' },
  { label: 'Chile', value: 'CL', dial_code: '+56' },
  { label: 'China', value: 'CN', dial_code: '+86' },
  { label: 'Christmas Island', value: 'CX', dial_code: '+61' },
  { label: 'Cocos (Keeling) Islands', value: 'CC', dial_code: '+61' },
  { label: 'Colombia', value: 'CO', dial_code: '+57' },
  { label: 'Comoros', value: 'KM', dial_code: '+269' },
  { label: 'Congo', value: 'CG', dial_code: '+242' },
  { label: 'Congo, The Democratic Republic of Congo', value: 'CD', dial_code: '+243' },
  { label: 'Cook Islands', value: 'CK', dial_code: '+682' },
  { label: 'Costa Rica', value: 'CR', dial_code: '+506' },
  { label: 'Cote d\'Ivoire', value: 'CI', dial_code: '+225' },
  { label: 'Croatia', value: 'HR', dial_code: '+385' },
  { label: 'Cuba', value: 'CU', dial_code: '+53' },
  { label: 'Cyprus', value: 'CY', dial_code: '+357' },
  { label: 'Czech Republic', value: 'CZ', dial_code: '+420' },
  { label: 'Denmark', value: 'DK', dial_code: '+45' },
  { label: 'Djibouti', value: 'DJ', dial_code: '+253' },
  { label: 'Dominica', value: 'DM', dial_code: '+1 767' },
  { label: 'Dominican Republic', value: 'DO', dial_code: '+1 849' },
  { label: 'Ecuador', value: 'EC', dial_code: '+593' },
  { label: 'Egypt', value: 'EG', dial_code: '+20' },
  { label: 'El Salvador', value: 'SV', dial_code: '+503' },
  { label: 'Equatorial Guinea', value: 'GQ', dial_code: '+240' },
  { label: 'Eritrea', value: 'ER', dial_code: '+291' },
  { label: 'Estonia', value: 'EE', dial_code: '+372' },
  { label: 'Ethiopia', value: 'ET', dial_code: '+251' },
  { label: 'Falkland Islands (Malvinas)', value: 'FK', dial_code: '+500' },
  { label: 'Faroe Islands', value: 'FO', dial_code: '+298' },
  { label: 'Fiji', value: 'FJ', dial_code: '+679' },
  { label: 'Finland', value: 'FI', dial_code: '+358' },
  { label: 'France', value: 'FR', dial_code: '+33' },
  { label: 'French Guiana', value: 'GF', dial_code: '+594' },
  { label: 'French Polynesia', value: 'PF', dial_code: '+689' },
  { label: 'Gabon', value: 'GA', dial_code: '+241' },
  { label: 'Gambia', value: 'GM', dial_code: '+220' },
  { label: 'Georgia', value: 'GE', dial_code: '+995' },
  { label: 'Germany', value: 'DE', dial_code: '+49' },
  { label: 'Ghana', value: 'GH', dial_code: '+233' },
  { label: 'Gibraltar', value: 'GI', dial_code: '+350' },
  { label: 'Greece', value: 'GR', dial_code: '+30' },
  { label: 'Greenland', value: 'GL', dial_code: '+299' },
  { label: 'Grenada', value: 'GD', dial_code: '+1 473' },
  { label: 'Guadeloupe', value: 'GP', dial_code: '+590' },
  { label: 'Guam', value: 'GU', dial_code: '+1 671' },
  { label: 'Guatemala', value: 'GT', dial_code: '+502' },
  { label: 'Guernsey', value: 'GG', dial_code: '+44' },
  { label: 'Guinea', value: 'GN', dial_code: '+224' },
  { label: 'Guinea-Bissau', value: 'GW', dial_code: '+245' },
  { label: 'Guyana', value: 'GY', dial_code: '+595' },
  { label: 'Haiti', value: 'HT', dial_code: '+509' },
  { label: 'Holy See (Vatican City State)', value: 'VA', dial_code: '+379' },
  { label: 'Honduras', value: 'HN', dial_code: '+504' },
  { label: 'Hong Kong', value: 'HK', dial_code: '+852' },
  { label: 'Hungary', value: 'HU', dial_code: '+36' },
  { label: 'Iceland', value: 'IS', dial_code: '+354' },
  { label: 'India', value: 'IN', dial_code: '+91' },
  { label: 'Indonesia', value: 'ID', dial_code: '+62' },
  { label: 'Iran, Islamic Republic of Gulf', value: 'IR', dial_code: '+98' },
  { label: 'Iraq', value: 'IQ', dial_code: '+964' },
  { label: 'Isle of', value: 'IM', dial_code: '+44' },
  { label: 'Israel', value: 'IL', dial_code: '+972' },
  { label: 'Italy', value: 'IT', dial_code: '+39' },
  { label: 'Jamaica', value: 'JM', dial_code: '+1 876' },
  { label: 'Japan', value: 'JP', dial_code: '+81' },
  { label: 'Jersey', value: 'JE', dial_code: '+44' },
  { label: 'Jordan', value: 'JO', dial_code: '+962' },
  { label: 'Kazakhstan', value: 'KZ', dial_code: '+7 7' },
  { label: 'Kenya', value: 'KE', dial_code: '+254' },
  { label: 'Kiribati', value: 'KI', dial_code: '+686' },
  { label: 'Korea, Democratic People\'s Republic of', value: 'KP', dial_code: '+850' },
  { label: 'Korea, Republic of Korea', value: 'KR', dial_code: '+82' },
  { label: 'Kuwait', value: 'KW', dial_code: '+965' },
  { label: 'Kyrgyzstan', value: 'KG', dial_code: '+996' },
  { label: 'Laos', value: 'LA', dial_code: '+856' },
  { label: 'Latvia', value: 'LV', dial_code: '+371' },
  { label: 'Lebanon', value: 'LB', dial_code: '+961' },
  { label: 'Lesotho', value: 'LS', dial_code: '+266' },
  { label: 'Liberia', value: 'LR', dial_code: '+231' },
  { label: 'Libyan Arab Jamahiriya', value: 'LY', dial_code: '+218' },
  { label: 'Liechtenstein', value: 'LI', dial_code: '+423' },
  { label: 'Lithuania', value: 'LT', dial_code: '+370' },
  { label: 'Luxembourg', value: 'LU', dial_code: '+352' },
  { label: 'Macao', value: 'MO', dial_code: '+853' },
  { label: 'Macedonia', value: 'MK', dial_code: '+389' },
  { label: 'Madagascar', value: 'MG', dial_code: '+261' },
  { label: 'Malawi', value: 'MW', dial_code: '+265' },
  { label: 'Malaysia', value: 'MY', dial_code: '+60' },
  { label: 'Maldives', value: 'MV', dial_code: '+960' },
  { label: 'Mali', value: 'ML', dial_code: '+223' },
  { label: 'Malta', value: 'MT', dial_code: '+356' },
  { label: 'Marshall Islands', value: 'MH', dial_code: '+692' },
  { label: 'Martinique', value: 'MQ', dial_code: '+596' },
  { label: 'Mauritania', value: 'MR', dial_code: '+222' },
  { label: 'Mauritius', value: 'MU', dial_code: '+230' },
  { label: 'Mayotte', value: 'YT', dial_code: '+262' },
  { label: 'Mexico', value: 'MX', dial_code: '+52' },
  { label: 'Micronesia, Federated States of', value: 'FM', dial_code: '+691' },
  { label: 'Moldova', value: 'MD', dial_code: '+373' },
  { label: 'Monaco', value: 'MC', dial_code: '+377' },
  { label: 'Mongolia', value: 'MN', dial_code: '+976' },
  { label: 'Montenegro', value: 'ME', dial_code: '+382' },
  { label: 'Montserrat', value: 'MS', dial_code: '+1664' },
  { label: 'Morocco', value: 'MA', dial_code: '+212' },
  { label: 'Mozambique', value: 'MZ', dial_code: '+258' },
  { label: 'Myanmar', value: 'MM', dial_code: '+95' },
  { label: 'Namibia', value: 'NA', dial_code: '+264' },
  { label: 'Nauru', value: 'NR', dial_code: '+674' },
  { label: 'Nepal', value: 'NP', dial_code: '+977' },
  { label: 'Netherlands', value: 'NL', dial_code: '+31' },
  { label: 'Netherlands Antilles', value: 'AN', dial_code: '+599' },
  { label: 'New Caledonia', value: 'NC', dial_code: '+687' },
  { label: 'Nicaragua', value: 'NI', dial_code: '+505' },
  { label: 'Niger', value: 'NE', dial_code: '+227' },
  { label: 'Nigeria', value: 'NG', dial_code: '+234' },
  { label: 'Niue', value: 'NU', dial_code: '+683' },
  { label: 'Norfolk Island', value: 'NF', dial_code: '+672' },
  { label: 'Northern Mariana Islands', value: 'MP', dial_code: '+1 670' },
  { label: 'Norway', value: 'NO', dial_code: '+47' },
  { label: 'Oman', value: 'OM', dial_code: '+968' },
  { label: 'Pakistan', value: 'PK', dial_code: '+92' },
  { label: 'Palau', value: 'PW', dial_code: '+680' },
  { label: 'Palestinian Territory, Occupied', value: 'PS', dial_code: '+970' },
  { label: 'Panama', value: 'PA', dial_code: '+507' },
  { label: 'Papua New Guinea', value: 'PG', dial_code: '+675' },
  { label: 'Paraguay', value: 'PY', dial_code: '+595' },
  { label: 'Peru', value: 'PE', dial_code: '+51' },
  { label: 'Philippines', value: 'PH', dial_code: '+63' },
  { label: 'Pitcairn', value: 'PN', dial_code: '+872' },
  { label: 'Poland', value: 'PL', dial_code: '+48' },
  { label: 'Portugal', value: 'PT', dial_code: '+351' },
  { label: 'Puerto Rico', value: 'PR', dial_code: '+1 939' },
  { label: 'Qatar', value: 'QA', dial_code: '+974' },
  { label: 'Romania', value: 'RO', dial_code: '+40' },
  { label: 'Russia', value: 'RU', dial_code: '+7' },
  { label: 'Rwanda', value: 'RW', dial_code: '+250' },
  { label: 'Reunion', value: 'RE', dial_code: '+262' },
  { label: 'Saint Barthelemy', value: 'BL', dial_code: '+590' },
  { label: 'Saint Helena, Ascension and Tristan Da Cunha', value: 'SH', dial_code: '+290' },
  { label: 'Saint Kitts and Nevis', value: 'KN', dial_code: '+1 869' },
  { label: 'Saint Lucia', value: 'LC', dial_code: '+1 758' },
  { label: 'Saint Martin', value: 'MF', dial_code: '+590' },
  { label: 'Saint Pierre and Miquelon', value: 'PM', dial_code: '+508' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC', dial_code: '+1 784' },
  { label: 'Samoa', value: 'WS', dial_code: '+685' },
  { label: 'San Marino', value: 'SM', dial_code: '+378' },
  { label: 'Sao Tome and Principe', value: 'ST', dial_code: '+239' },
  { label: 'Saudi Arabia', value: 'SA', dial_code: '+966' },
  { label: 'Senegal', value: 'SN', dial_code: '+221' },
  { label: 'Serbia', value: 'RS', dial_code: '+381' },
  { label: 'Seychelles', value: 'SC', dial_code: '+248' },
  { label: 'Sierra Leone', value: 'SL', dial_code: '+232' },
  { label: 'Singapore', value: 'SG', dial_code: '+65' },
  { label: 'Slovakia', value: 'SK', dial_code: '+421' },
  { label: 'Slovenia', value: 'SI', dial_code: '+386' },
  { label: 'Solomon Islands', value: 'SB', dial_code: '+677' },
  { label: 'Somalia', value: 'SO', dial_code: '+252' },
  { label: 'South Africa', value: 'ZA', dial_code: '+27' },
  { label: 'South Georgia and the South Sandwich Islands', value: 'GS', dial_code: '+500' },
  { label: 'Spain', value: 'ES', dial_code: '+34' },
  { label: 'Sri Lanka', value: 'LK', dial_code: '+94' },
  { label: 'Sudan', value: 'SD', dial_code: '+249' },
  { label: 'Suriname', value: 'SR', dial_code: '+597' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ', dial_code: '+47' },
  { label: 'Swaziland', value: 'SZ', dial_code: '+268' },
  { label: 'Sweden', value: 'SE', dial_code: '+46' },
  { label: 'Switzerland', value: 'CH', dial_code: '+41' },
  { label: 'Syrian Arab Republic', value: 'SY', dial_code: '+963' },
  { label: 'Taiwan', value: 'TW', dial_code: '+886' },
  { label: 'Tajikistan', value: 'TJ', dial_code: '+992' },
  { label: 'Tanzania, United Republic of', value: 'TZ', dial_code: '+255' },
  { label: 'Thailand', value: 'TH', dial_code: '+66' },
  { label: 'Timor-Leste', value: 'TL', dial_code: '+670' },
  { label: 'Togo', value: 'TG', dial_code: '+228' },
  { label: 'Tokelau', value: 'TK', dial_code: '+690' },
  { label: 'Tonga', value: 'TO', dial_code: '+676' },
  { label: 'Trinidad and Tobago', value: 'TT', dial_code: '+1 868' },
  { label: 'Tunisia', value: 'TN', dial_code: '+216' },
  { label: 'Turkey', value: 'TR', dial_code: '+90' },
  { label: 'Turkmenistan', value: 'TM', dial_code: '+993' },
  { label: 'Turks and Caicos Islands', value: 'TC', dial_code: '+1 649' },
  { label: 'Tuvalu', value: 'TV', dial_code: '+688' },
  { label: 'Uganda', value: 'UG', dial_code: '+256' },
  { label: 'Ukraine', value: 'UA', dial_code: '+380' },
  { label: 'United Arab Emirates', value: 'AE', dial_code: '+971' },
  { label: 'Uruguay', value: 'UY', dial_code: '+598' },
  { label: 'Uzbekistan', value: 'UZ', dial_code: '+998' },
  { label: 'Vanuatu', value: 'VU', dial_code: '+678' },
  { label: 'Venezuela, Bolivarian Republic of', value: 'VE', dial_code: '+58' },
  { label: 'Vietnam', value: 'VN', dial_code: '+84' },
  { label: 'Virgin Islands, British', value: 'VG', dial_code: '+1 284' },
  { label: 'Virgin Islands, U.S.', value: 'VI', dial_code: '+1 340' },
  { label: 'Wallis and Futuna', value: 'WF', dial_code: '+681' },
  { label: 'Yemen', value: 'YE', dial_code: '+967' },
  { label: 'Zambia', value: 'ZM', dial_code: '+260' },
  { label: 'Zimbabwe', value: 'ZW', dial_code: '+263' }
]
