---
steps:
  - type: "waiter"

  - name: ":docker:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: native

  - type: "waiter"

  - name: ":pill:"
    command: "bin/buildkite bin/ci run npm test"
    agents:
      queue: native

  - type: "waiter"

  - name: ":loudspeaker:"
    command: "bin/buildkite bin/ci announce released"
    agents:
      queue: native
