---
steps:
  - type: "waiter"

  - name: ":docker:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: build

  - type: "waiter"

  - name: ":pill: lint"
    command: "bin/buildkite bin/ci run npm run lint"

  - name: ":pill: test"
    command: "bin/buildkite bin/ci run npm test"

  - type: "waiter"

  - name: ":package: Deploy"
    command: "bin/buildkite bin/only-for-version-releases bin/ci run bin/deploy"
    branches: "master"

  - type: "waiter"

  - name: ":loudspeaker:"
    command: "bin/buildkite bin/only-for-version-releases bin/ci announce released"
    branches: "master"
