---
steps:
  - type: "waiter"

  - name: ":docker:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: native

  - type: "waiter"

  - name: ":pill:"
    command: "bin/buildkite bin/ci run npm test"
    agents:
      queue: native

  - name: ":rocket: Release"
    type: "manual"

  - name: ":s3: Delploy assets"
    command: "bin/buildkite bin/ci run bin/deploy_assets"
    branches: "master"
    agents:
      queue: native

  - type: "waiter"

  - name: ":package: Publish"
    command: "bin/buildkite bin/ci run bin/publish_npm"
    branches: "master"
    agents:
      queue: native
