'use strict'

import React from 'react'
import FilterSelect from '../../../forms/FilterSelect'

export default React.createClass({
  displayName: 'FilterSelectExample',

  render () {
    let options = [
      { label: 'Fred Hollows Foundation', value: '1' },
      { label: 'Australian Red Cross', value: '2' },
      { label: 'Indigenous Literacy Foundation', value: '3' },
      { label: 'Australian Men’s Shed Association', value: '4' },
      { label: 'Royal Flying Doctor Service', value: '5' },
      { label: 'Lifeline', value: '6' },
      { label: 'Fitted For Work', value: '7' },
      { label: 'Thin Green Line Foundation', value: '8' },
      { label: 'The Smith Family', value: '9' },
      { label: 'Exodus Foundation', value: '10' },
      { label: 'Fred Hollows Foundation', value: '11' },
      { label: 'Australian Red Cross', value: '12' },
      { label: 'Indigenous Literacy Foundation', value: '13' },
      { label: 'Australian Men’s Shed Association', value: '14' },
      { label: 'Royal Flying Doctor Service', value: '15' },
      { label: 'Lifeline', value: '16' },
      { label: 'Fitted For Work', value: '17' },
      { label: 'Thin Green Line Foundation', value: '18' },
      { label: 'The Smith Family', value: '19' },
      { label: 'Exodus Foundation', value: '20' },
      { label: 'Fred Hollows Foundation', value: '21' },
      { label: 'Australian Red Cross', value: '22' },
      { label: 'Indigenous Literacy Foundation', value: '23' },
      { label: 'Australian Men’s Shed Association', value: '24' },
      { label: 'Royal Flying Doctor Service', value: '25' },
      { label: 'Lifeline', value: '26' },
      { label: 'Fitted For Work', value: '27' },
      { label: 'Thin Green Line Foundation', value: '28' },
      { label: 'The Smith Family', value: '29' },
      { label: 'Exodus Foundation', value: '30' },
      { label: 'Fred Hollows Foundation', value: '31' },
      { label: 'Australian Red Cross', value: '32' },
      { label: 'Indigenous Literacy Foundation', value: '33' },
      { label: 'Australian Men’s Shed Association', value: '34' },
      { label: 'Royal Flying Doctor Service', value: '35' },
      { label: 'Lifeline', value: '36' },
      { label: 'Fitted For Work', value: '37' },
      { label: 'Thin Green Line Foundation', value: '38' },
      { label: 'The Smith Family', value: '39' },
      { label: 'Exodus Foundation', value: '40' },
      { label: 'Fred Hollows Foundation', value: '41' },
      { label: 'Australian Red Cross', value: '42' },
      { label: 'Indigenous Literacy Foundation', value: '43' },
      { label: 'Australian Men’s Shed Association', value: '44' },
      { label: 'Royal Flying Doctor Service', value: '45' },
      { label: 'Lifeline', value: '46' },
      { label: 'Fitted For Work', value: '47' },
      { label: 'Thin Green Line Foundation', value: '48' },
      { label: 'The Smith Family', value: '49' },
      { label: 'Exodus Foundation', value: '50' },
      { label: 'Fred Hollows Foundation', value: '1' },
      { label: 'Australian Red Cross', value: '2' },
      { label: 'Indigenous Literacy Foundation', value: '3' },
      { label: 'Australian Men’s Shed Association', value: '4' },
      { label: 'Royal Flying Doctor Service', value: '5' },
      { label: 'Lifeline', value: '6' },
      { label: 'Fitted For Work', value: '7' },
      { label: 'Thin Green Line Foundation', value: '8' },
      { label: 'The Smith Family', value: '9' },
      { label: 'Exodus Foundation', value: '10' },
      { label: 'Fred Hollows Foundation', value: '11' },
      { label: 'Australian Red Cross', value: '12' },
      { label: 'Indigenous Literacy Foundation', value: '13' },
      { label: 'Australian Men’s Shed Association', value: '14' },
      { label: 'Royal Flying Doctor Service', value: '15' },
      { label: 'Lifeline', value: '16' },
      { label: 'Fitted For Work', value: '17' },
      { label: 'Thin Green Line Foundation', value: '18' },
      { label: 'The Smith Family', value: '19' },
      { label: 'Exodus Foundation', value: '20' },
      { label: 'Fred Hollows Foundation', value: '21' },
      { label: 'Australian Red Cross', value: '22' },
      { label: 'Indigenous Literacy Foundation', value: '23' },
      { label: 'Australian Men’s Shed Association', value: '24' },
      { label: 'Royal Flying Doctor Service', value: '25' },
      { label: 'Lifeline', value: '26' },
      { label: 'Fitted For Work', value: '27' },
      { label: 'Thin Green Line Foundation', value: '28' },
      { label: 'The Smith Family', value: '29' },
      { label: 'Exodus Foundation', value: '30' },
      { label: 'Fred Hollows Foundation', value: '31' },
      { label: 'Australian Red Cross', value: '32' },
      { label: 'Indigenous Literacy Foundation', value: '33' },
      { label: 'Australian Men’s Shed Association', value: '34' },
      { label: 'Royal Flying Doctor Service', value: '35' },
      { label: 'Lifeline', value: '36' },
      { label: 'Fitted For Work', value: '37' },
      { label: 'Thin Green Line Foundation', value: '38' },
      { label: 'The Smith Family', value: '39' },
      { label: 'Exodus Foundation', value: '40' },
      { label: 'Fred Hollows Foundation', value: '41' },
      { label: 'Australian Red Cross', value: '42' },
      { label: 'Indigenous Literacy Foundation', value: '43' },
      { label: 'Australian Men’s Shed Association', value: '44' },
      { label: 'Royal Flying Doctor Service', value: '45' },
      { label: 'Lifeline', value: '46' },
      { label: 'Fitted For Work', value: '47' },
      { label: 'Thin Green Line Foundation', value: '48' },
      { label: 'The Smith Family', value: '49' },
      { label: '100 Exodus Foundation', value: '100' },
      { label: 'Fred Hollows Foundation', value: '1' },
      { label: 'Australian Red Cross', value: '2' },
      { label: 'Indigenous Literacy Foundation', value: '3' },
      { label: 'Australian Men’s Shed Association', value: '4' },
      { label: 'Royal Flying Doctor Service', value: '5' },
      { label: 'Lifeline', value: '6' },
      { label: 'Fitted For Work', value: '7' },
      { label: 'Thin Green Line Foundation', value: '8' },
      { label: 'The Smith Family', value: '9' },
      { label: 'Exodus Foundation', value: '10' },
      { label: 'Fred Hollows Foundation', value: '11' },
      { label: 'Australian Red Cross', value: '12' },
      { label: 'Indigenous Literacy Foundation', value: '13' },
      { label: 'Australian Men’s Shed Association', value: '14' },
      { label: 'Royal Flying Doctor Service', value: '15' },
      { label: 'Lifeline', value: '16' },
      { label: 'Fitted For Work', value: '17' },
      { label: 'Thin Green Line Foundation', value: '18' },
      { label: 'The Smith Family', value: '19' },
      { label: 'Exodus Foundation', value: '20' },
      { label: 'Fred Hollows Foundation', value: '21' },
      { label: 'Australian Red Cross', value: '22' },
      { label: 'Indigenous Literacy Foundation', value: '23' },
      { label: 'Australian Men’s Shed Association', value: '24' },
      { label: 'Royal Flying Doctor Service', value: '25' },
      { label: 'Lifeline', value: '26' },
      { label: 'Fitted For Work', value: '27' },
      { label: 'Thin Green Line Foundation', value: '28' },
      { label: 'The Smith Family', value: '29' },
      { label: 'Exodus Foundation', value: '30' },
      { label: 'Fred Hollows Foundation', value: '31' },
      { label: 'Australian Red Cross', value: '32' },
      { label: 'Indigenous Literacy Foundation', value: '33' },
      { label: 'Australian Men’s Shed Association', value: '34' },
      { label: 'Royal Flying Doctor Service', value: '35' },
      { label: 'Lifeline', value: '36' },
      { label: 'Fitted For Work', value: '37' },
      { label: 'Thin Green Line Foundation', value: '38' },
      { label: 'The Smith Family', value: '39' },
      { label: 'Exodus Foundation', value: '40' },
      { label: 'Fred Hollows Foundation', value: '41' },
      { label: 'Australian Red Cross', value: '42' },
      { label: 'Indigenous Literacy Foundation', value: '43' },
      { label: 'Australian Men’s Shed Association', value: '44' },
      { label: 'Royal Flying Doctor Service', value: '45' },
      { label: 'Lifeline', value: '46' },
      { label: 'Fitted For Work', value: '47' },
      { label: 'Thin Green Line Foundation', value: '48' },
      { label: 'The Smith Family', value: '49' },
      { label: 'Exodus Foundation', value: '50' }
    ]

    return (
      <div>
        <h3 className="DemoPage__h3" id="FilterSelect">FilterSelect WAT</h3>

        <FilterSelect
          value="2"
          options={ options } />

        <FilterSelect
          label={ null }
          value="2"
          options={ options } />
      </div>
    )
  }
})
